### ISSUE TITLE
Credit where credit is due!!

### ISSUE THREAD

**Issue by 3alqassab** [nandorojo/react-native-iconic#1]
Hello sorry for opening an issue for this. 

I'm new to "open-sourcing"  and I have created a package to do the same as yours but for Font Awesome 6. 
_(IDK if it already exists or not but I wanted to try to do it, so I did!)_

The package can be found [Here!](https://github.com/404-Software/fontawesome)

I was wondering what would be the best way to credit you?

Many thanks.

**Comment by nandorojo** [comment]
hey, nice job! welcome to the world of open source.

at the top of the readme, you can write something like this:

## Credits

This package is a fork of [`react-native-iconic` by Fernando Rojo](https://github.com/nandorojo/react-native-iconic).
